kind: pipeline
type: docker
name: default

steps:
- name: update
  image: composer
  commands:
  - composer update --ignore-platform-req=ext-intl

- name: install
  image: composer
  commands:
  - composer install --ignore-platform-req=ext-intl

- name: test phpunit
  image: php:8
  commands:
  - vendor/bin/phpunit --configuration config.xml

- name: update integration
  image: appleboy/drone-scp
  settings:
    host: 212.227.12.57
    username: root
    password: 02@g$F*jat
    port: 22
    command_timeout: 2m
    target: /var/www/html/clmad_app
    source: ./
    
