kind: pipeline
type: docker
name: default

steps:
- name: update
  image: composer
  commands:
  - composer update --ignore-platform-req=ext-intl

- name: install
  image: composer
  commands:
  - composer install --ignore-platform-req=ext-intl

- name: update integration
  image: appleboy/drone-scp
  settings:
    host: 212.227.12.57
    username: root
    password: 02@g$F*jat
    port: 22
    command_timeout: 2m
    target: /var/www/html/clmad_app
    source: ./
    
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host: 
      from_secret: http://212.227.12.57:9000
    sonar_token:
      from_secret: squ_8c2ff936d25f9a29314ec64f5615fa0f7c1280d9
    
