kind: pipeline
type: docker
name: default

server:
  host: 212.217.12.57
  user: root
  password: 02@g$F*jat

steps:
- name: update
  image: composer
  commands:
  - composer update --ignore-platform-req=ext-intl

- name: install
  image: composer
  commands:
  - composer install

- name: deploy
  commands:
  - mkdir -p /var/www/html/clmad_app
  - cp -rf * /var/www/html/clmad_app