kind: pipeline
name: default

steps:
# - name: test
#   image: maven:3.6.3-openjdk-11
#   commands:
#   - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#   - mvn test -B

- name: build
  image: maven:3.6.3-openjdk-11
  commands:
  - mvn package -DskipTests=true