kind: pipeline
type: docker
name: default

steps:
- name: update
  image: composer
  commands:
  - composer update --ignore-platform-req=ext-intl

- name: install
  image: composer
  commands:
  - composer install --ignore-platform-req=ext-intl

- name: test
  image: php:8
  commands:
  - vendor/bin/phpunit --configuration config.xml